### ISSUE TITLE
Analytics-engine-v3 instance show id

### ISSUE THREAD

**Issue by migugf1234** [ibm-cloud-docs/analytics-engine-cli-plugin#2]
In the documentation says ibmcloud analytics-engine-v3 instance show --id ID but it doesn't work the proper command is ibmcloud ae-v3 instance show -i ID

**Comment by gabydreckschmidt** [comment]
@migugf1234 I tried looking for this incorrect occurrence but couldn't find it. Could you please provide the link to the topic? Thank you!

**Comment by migugf1234** [comment]
Here you are the link: https://cloud.ibm.com/docs/cli?topic=analytics-engine-cli-plugin-CLI_analytics_engine

just search for: "https://cloud.ibm.com/docs/cli?topic=analytics-engine-cli-plugin-CLI_analytics_engine"

the option --id doesn't work.

**Comment by gabydreckschmidt** [comment]
@migugf1234 the Analytics Engine dev team tested this, here their answer:

Hi Gaby,

I have tested and "ibmcloud analytics-engine-v3 instance show --id ID" is working as expected.
Here is the snippet.

silpidhua@SILPIs-MacBook-Pro WORK % export IBM_ANALYTICS_ENGINE_API_URL=https://api.us-south.ae.cloud.ibm.com        

silpidhua@SILPIs-MacBook-Pro WORK % ibmcloud ae-v3 instance show --id af7b8b6d-d3b8-44d7-a44b-69dea5b0f776   

...

Performing the requested operation on target instance ID af7b8b6d-d3b8-44d7-a44b-69dea5b0f776

                       

id                  af7b8b6d-d3b8-44d7-a44b-69dea5b0f776   

state               active   

state_change_time   2022-05-27T06:29:43.000Z   

default_runtime     <Nested Object>   

instance_home       <Nested Object>   

silpidhua@SILPIs-MacBook-Pro WORK % ibmcloud ae-v3 instance show -id af7b8b6d-d3b8-44d7-a44b-69dea5b0f776 

...

Performing the requested operation on target instance ID d

FAILED



code                 message   

resource_not_found   The URL in your request is invalid. Specify a valid URL and send the request again.
